version: '3.7'

services:
# set up database container
  pgdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Welcome1
      POSTGRES_USER: postgres
      POSTGRES_DB: restaurant-db
    container_name: postgres
    ports:
      - $PG_PORT:${PG_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_dump:/docker-entrypoint-initdb.d

# setup server container
  server:
    build: .
    depends_on:
      - pgdb  
    environment:
      DB_HOST: pgdb
      DB_USER: postgres
      DB_NAME: restaurant-db
      DATABASE_URL: postgres://postgres:Welcome1@pgdb:5432/restaurant-db
    ports:
      - '8080:8080'
      - '9229:9229'
    tty: true

#setup client container

  client:
    build: ./client

    ports:
      - '3000:3000'
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/public:/srv/app/client/public
    links:
      - server
    depends_on:
      - server
    tty: true
volumes:
  pgdata:    

